<?php
  
$labels = array();
$labels['filters'] = 'Filter';
$labels['storedfilters'] = 'Sparade filterregler';
$labels['whatfilter'] = 'Filterkriterium';
$labels['searchstring'] = 'Innehåller';
$labels['moveto'] = 'Flytta till';
$labels['from'] = 'Från';
$labels['to'] = 'Till';
$labels['cc'] = 'CC';
$labels['subject'] = 'Ämne';
$labels['delete'] = 'Ta bort';
$labels['filterpriority'] = 'Applicera inte fler filterregler';

$messages = array();
$messages['nosearchstring'] = "Fältet 'Innehåller' kan inte lämnas tomt.";
$messages['successfullysaved'] = "Filterregeln sparad.";
$messages['unsuccessfullysaved'] = "Fel: filterregerln inte sparad.";
$messages['successfullydeleted'] = "Filterregeln borttagen.";
$messages['unsuccessfullydeleted'] = "Fel: filterregeln inte borttagen.";
$messages['msg_if_field'] = 'Om fältet';
$messages['msg_contains'] = 'innehåller';
$messages['msg_move_msg_in'] = 'flytta meddelandent till';
$messages['msg_no_stored_filters'] = "Det finns inga sparade filterregler.";

?>
